name: CovMix
channels:
    - bioconda
    - conda-forge
dependencies:
    - bwa
    - mafft
    - python=3
    - scipy
    - iqtree
    - samtools
    - snakemake=6.2.1
    - vsearch
    - seqtk
    - r-base
    - r-ggplot2
    - bioconductor-ggtree=2.2.1
    - r-reshape2
    - r-rvcheck=0.1.8
    - r-dplyr<=1.0.0
    - numpy
    - biopython
    - ete3
    - pandas
    - matplotlib
    - poppler
    - varscan
    - bam-readcount 
